name: firebase_storage
description: Flutter plugin for Firebase Cloud Storage, a powerful, simple, and
  cost-effective object storage service for Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage
version: 3.0.6

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.storage
        pluginClass: FirebaseStoragePlugin
      ios:
        pluginClass: FLTFirebaseStoragePlugin
      web:
        pluginClass: FirebaseStoragePlugin
        fileName: firebase_storage_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^0.4.0
  local_file_reference:
    git: https://github.com/buntagonalprism/local_file_reference.git

dev_dependencies:
  http: ^0.12.0
  flutter_test:
    sdk: flutter
  uuid: "^1.0.0"
  flutter_driver:
    sdk: flutter
  test: any

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
