name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../
  firebase_core:
    git: 
      url: https://github.com/buntagonalprism/flutterfire.git
      ref: web-support
      path: packages/firebase_core

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
