name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_storage:
    path: ../
  firebase_core:
    git: 
      url: https://github.com/buntagonalprism/flutterfire.git
      ref: web-support
      path: packages/firebase_core
  uuid: ^1.0.0
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

